In [8]:
import pandas as pd
import numpy as np

data = {
    "Student_ID": ["S01","S02","S03","S04","S05","S06","S07","S08"],
    "Age": [20,21,22,np.nan,20,23,21,22],
    "Marks": [85,np.nan,92,45,300,78,65,np.nan],
    "Attendance": [90,75,95,40,85,np.nan,70,60],
    "Gender": ["Male","Female","Male","Female","Male","Female","Male","Female"],
    "Department": ["CS","IT","CS","IT","CS","CS","IT","CS"]
}

df = pd.DataFrame(data)
df

  Student_ID   Age  Marks  Attendance  Gender Department
0        S01  20.0   85.0        90.0    Male         CS
1        S02  21.0    NaN        75.0  Female         IT
2        S03  22.0   92.0        95.0    Male         CS
3        S04   NaN   45.0        40.0  Female         IT
4        S05  20.0  300.0        85.0    Male         CS
5        S06  23.0   78.0         NaN  Female         CS
6        S07  21.0   65.0        70.0    Male         IT
7        S08  22.0    NaN        60.0  Female         CS

In [9]:
print(df)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("\nData Types:\n", df.dtypes)

  Student_ID   Age  Marks  Attendance  Gender Department
0        S01  20.0   85.0        90.0    Male         CS
1        S02  21.0    NaN        75.0  Female         IT
2        S03  22.0   92.0        95.0    Male         CS
3        S04   NaN   45.0        40.0  Female         IT
4        S05  20.0  300.0        85.0    Male         CS
5        S06  23.0   78.0         NaN  Female         CS
6        S07  21.0   65.0        70.0    Male         IT
7        S08  22.0    NaN        60.0  Female         CS
Rows: 8
Columns: 6

Data Types:
 Student_ID        str
Age           float64
Marks         float64
Attendance    float64
Gender            str
Department        str
dtype: object

In [10]:
print("Missing values:\n",df.isnull().sum())
print("Duplicate records:\n", df.duplicated().sum())

Missing values:
 Student_ID    0
Age           1
Marks         2
Attendance    1
Gender        0
Department    0
dtype: int64
Duplicate records:
 0

In [11]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df

  Student_ID   Age  Marks  Attendance  Gender Department
0        S01  20.0   85.0        90.0    Male         CS
1        S02  21.0    NaN        75.0  Female         IT
2        S03  22.0   92.0        95.0    Male         CS
3        S04  21.0   45.0        40.0  Female         IT
4        S05  20.0  300.0        85.0    Male         CS
5        S06  23.0   78.0         NaN  Female         CS
6        S07  21.0   65.0        70.0    Male         IT
7        S08  22.0    NaN        60.0  Female         CS